### ISSUE TITLE
Technical Challenges

### ISSUE THREAD

**Issue by barnjamin** [n-elia/algobet#1]
Hello! Thanks for using Beaker to build this!

I'd love to get some more feedback on the issues you encountered along the way

> the documentation is still insufficient to cover all its functionalities.

Where did you find docs most lacking? Any other issues not covered in the readme you came across?

**Comment by n-elia** [comment]
Hi Ben, thanks for asking!

First of all, let me say that is has been a pleasure to use Beaker. It's been a much more pleasant experience than bare PyTeal!

We found the [beaker/examples](https://github.com/algorand-devrel/beaker/tree/master/examples) to cover most of the functionalities that Beaker has to offer. However, we would have appreciated a lot a sort of "landing page" which gives an idea of which features are shown by each example. For instance, it would have been great to know a-priori that `amm` example includes an example of integration with pytest, or that `c2c` contains a showcase of `Precompile` feature for building contracts in a parent-child fashion.

Some other things that - *in our opinion* - would have been helpful to have in the [docs](https://algorand-devrel.github.io/beaker/html/index.html) pages:
* A usage example of `Authorize.opted_in` when you want to require that an account has opted-in your application. We got in touch on Discord and you consequently set the current application ID as default parameter (https://github.com/algorand-devrel/beaker/issues/93) and I think that it should be put into the docs, too.
*  `ApplicationClient` makes things a lot easier during contracts testing/demo. It may also allow to write down a basic contract client for contracts showcase purposes. I believe that there should be a suggestion about using `ApplicationClient` to interact with an already deployed contract by instantiating it with an existing application ID.
* We'd also appreciated an explicit reference to TEAL code export (maybe [here](https://algorand-devrel.github.io/beaker/html/usage.html#:~:text=an%20external%20method-,Compiled%20it%20to%20TEAL,-Done%20automatically%20by)?), which we only found in `calculator.py` example.

That's what we can recall, so far! Please feel free of asking more, if needed.

Let me finally thank you for your precious support on Discord server, very appreciated!

**Comment by barnjamin** [comment]
Fantastic feedback, thank you!

Happy to take any more feedback here, issues in Beaker, and of course Discord 🤝
